### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by ismartspace** [OpenLiberty/guide-maven-intro#43]
### Checklist for Review
**Through the browser:**
- [x] Read over guide and run through all commands (copy and paste using browser etc..)
- [x] Test the actual application (use it, hit endpoints, etc.)
- [x] No files in the middle panel (guide section)
- [x] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [x] Make sure hotspots actually point to the correct lines
- [x] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [x] All code commands are highlighting the right code
- [x] Any actions to look at the code should be a hotspot
- [x] Guide attribution is present
- [x] Any links are hyperlinks with the webpage title not the URL
- [x] Feature versions should not be included in the guide

**In the README.adoc:**
- [x] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [x] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [x] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
    - [x] start directory
    - [ ] finish directory
- [x] Files are formatted correctly
- [x] .travis.yaml file is updated accordingly

**Comment by ismartspace** [comment]
- [ ] start/pom.xml file does not exist

**Comment by andrewdes** [comment]
**NOTE:** This guide has the issue/blocker where one hotspot needs to highlight different lines of code.

**Comment by justineechen** [comment]
### Checklist for Post-Review
**Through the browser:**
- [ ] Read through guide, making sure that the flow of the guide is good
- [ ] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [ ] Run Acrolinx

**Comment by andrewdes** [comment]
>  In Creating a simple application, pom.xml should be a hotspot

I disagree, specifically because the sentence reads: "Using the standard directory structure saves you from customizing the pom.xml file **later.**" So the user has not yet been introduced to the `pom.xml` file and it is evident that they will be later in this guide. 

> In Creating the project POM file, pom.xml should be a hotspot

This section was weird, especially for the following sentence: "The pom.xml file provided for you in the start directory starts with a root `<project/>` element and `<modelversion/>`, which is always set to 4.0.0." 

Simply because the `pom.xml` file provided in the start directory is a barebones `pom.xml` file and is not a fully complete one like in the finish directory. So, if we hotspot to the `pom.xml` file in the start directory, would it get too confusing jumping back and forth between the `pom.xml` in the finish directory and the `pom.xml` in the start directory? Perhaps we should get more opinions on this

**Comment by andrewdes** [comment]
2nd Round Review:
- [x] guide author
- [x] branch is up to date with master
- [ ] mvn insturctions

 ```
cd finish
mvn install liberty:start-server
```
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server
- [ ] update the version of cxf-rt-rs-client and cxf-rt-rs-extension-providers to 3.2.6

**Comment by andrewdes** [comment]
**NOTE**: This guide has the issue/blocker where one hotspot needs to highlight different lines of code.

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
